version: "3.9"
services:
  

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - ./DATA:/data/db


  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    
  api:
    container_name: api
    build: ./server
    ports:
      - 8800:8800
    volumes:
      - ./server:/api
    environment:
      - PORT=8800
    # depends_on:
    #   - mongo

  front:
    container_name: front
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000

  
